repos:
-   repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      exclude: ^.*\b(migrations)\b.*$

