repos:
-   repo: 'https://github.com/psf/black'
    rev: 22.3.0
    hooks:
    - id: black
      exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pycqa/flake8
    rev: '6.0.0'
    hooks:
    - id: flake8
      exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
    - id: mypy
      exclude: ^.*\b(migrations)\b.*$
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
    - id: isort
      name: isort (cython)
      types: [cython]
    - id: isort
      name: isort (pyi)
      types: [pyi]
