version: "3.7"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5000:5432
    container_name: postgres_db
    environment:
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${DATABASE_USERNAME}
  app:
    build: .
    volumes:
      - .:/car_platform
    ports:
      - 8000:8000
    image: app:car_platform
    container_name: car_platform
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}

