# Generated by Django 4.2.7 on 2023-11-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100, verbose_name='Car model name')),
                ('engine_power', models.PositiveSmallIntegerField(verbose_name='Car engine power')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
    ]
