# Generated by Django 4.2.7 on 2023-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_platform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Feature name')),
                ('description', models.CharField(max_length=100, verbose_name='Feature description')),
            ],
            options={
                'db_table': 'Feature',
            },
        ),
        migrations.AddField(
            model_name='car',
            name='features',
            field=models.ManyToManyField(to='car_platform.feature'),
        ),
    ]
