# Generated by Django 4.2.7 on 2023-11-28 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_platform', '0002_feature_car_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.CharField(max_length=250, null=True, verbose_name='Car description'),
        ),
    ]
