# Generated by Django 4.2.7 on 2023-11-28 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_number', models.CharField(max_length=9, unique=True)),
                ('identification_number', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'db_table': 'Passport',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='passport',
            field=models.OneToOneField(default=1111111111, on_delete=django.db.models.deletion.CASCADE, to='user.passport'),
            preserve_default=False,
        ),
    ]
